//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPLabs.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        int Sub(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mul", ReplyAction="*")]
        int Mul(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MulAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Div", ReplyAction="*")]
        float Div(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Div", ReplyAction="*")]
        System.Threading.Tasks.Task<float> DivAsync(int a, int b);
        
        // CODEGEN: Контракт генерации сообщений с именем arr из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NumberOfNaturalEvenNumbers", ReplyAction="*")]
        ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersResponse NumberOfNaturalEvenNumbers(ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NumberOfNaturalEvenNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersResponse> NumberOfNaturalEvenNumbersAsync(ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberOfNaturalEvenNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberOfNaturalEvenNumbers", Namespace="http://tempuri.org/", Order=0)]
        public ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequestBody Body;
        
        public NumberOfNaturalEvenNumbersRequest() {
        }
        
        public NumberOfNaturalEvenNumbersRequest(ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NumberOfNaturalEvenNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ASPLabs.ServiceReference.ArrayOfInt arr;
        
        public NumberOfNaturalEvenNumbersRequestBody() {
        }
        
        public NumberOfNaturalEvenNumbersRequestBody(ASPLabs.ServiceReference.ArrayOfInt arr) {
            this.arr = arr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberOfNaturalEvenNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberOfNaturalEvenNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersResponseBody Body;
        
        public NumberOfNaturalEvenNumbersResponse() {
        }
        
        public NumberOfNaturalEvenNumbersResponse(ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NumberOfNaturalEvenNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NumberOfNaturalEvenNumbersResult;
        
        public NumberOfNaturalEvenNumbersResponseBody() {
        }
        
        public NumberOfNaturalEvenNumbersResponseBody(int NumberOfNaturalEvenNumbersResult) {
            this.NumberOfNaturalEvenNumbersResult = NumberOfNaturalEvenNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ASPLabs.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ASPLabs.ServiceReference.WebServiceSoap>, ASPLabs.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public int Sub(int a, int b) {
            return base.Channel.Sub(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(int a, int b) {
            return base.Channel.SubAsync(a, b);
        }
        
        public int Mul(int a, int b) {
            return base.Channel.Mul(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MulAsync(int a, int b) {
            return base.Channel.MulAsync(a, b);
        }
        
        public float Div(int a, int b) {
            return base.Channel.Div(a, b);
        }
        
        public System.Threading.Tasks.Task<float> DivAsync(int a, int b) {
            return base.Channel.DivAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersResponse ASPLabs.ServiceReference.WebServiceSoap.NumberOfNaturalEvenNumbers(ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequest request) {
            return base.Channel.NumberOfNaturalEvenNumbers(request);
        }
        
        public int NumberOfNaturalEvenNumbers(ASPLabs.ServiceReference.ArrayOfInt arr) {
            ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequest inValue = new ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequest();
            inValue.Body = new ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequestBody();
            inValue.Body.arr = arr;
            ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersResponse retVal = ((ASPLabs.ServiceReference.WebServiceSoap)(this)).NumberOfNaturalEvenNumbers(inValue);
            return retVal.Body.NumberOfNaturalEvenNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersResponse> ASPLabs.ServiceReference.WebServiceSoap.NumberOfNaturalEvenNumbersAsync(ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequest request) {
            return base.Channel.NumberOfNaturalEvenNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersResponse> NumberOfNaturalEvenNumbersAsync(ASPLabs.ServiceReference.ArrayOfInt arr) {
            ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequest inValue = new ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequest();
            inValue.Body = new ASPLabs.ServiceReference.NumberOfNaturalEvenNumbersRequestBody();
            inValue.Body.arr = arr;
            return ((ASPLabs.ServiceReference.WebServiceSoap)(this)).NumberOfNaturalEvenNumbersAsync(inValue);
        }
    }
}
