//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseBook
    {
        public int Id { get; set; }
        public int PacientDetailsId { get; set; }
        public int DoctorId { get; set; }
        public int DiseaseId { get; set; }
        public string Advice { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual PacientDetail PacientDetail { get; set; }
    }
}
