//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacientDetail
    {
        public PacientDetail()
        {
            this.DiseaseBooks = new HashSet<DiseaseBook>();
            this.PacientAddresses = new HashSet<PacientAddress>();
        }
    
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    
        public virtual ICollection<DiseaseBook> DiseaseBooks { get; set; }
        public virtual Pacient Pacient { get; set; }
        public virtual ICollection<PacientAddress> PacientAddresses { get; set; }
    }
}
